### ISSUE TITLE
List Module Improvements: bulk add, break across columns 

### ISSUE THREAD

**Issue by jamesdbarratt** [beaverbuilder/feature-requests#297]
I really like the list module, but I find it a bit cumbersome to work with when I am trying to add a longer list to the site. These are a few improvements that would make my life a lot easier!
 
1: Add the ability to bulk-add items to the list. Ideally, I would like to copy a list of items in which each new line is a new list item. The interface could allow users to select if they want the bulk-added text to be in the heading text or the content text.

2: Allow the list items to break across columns. I would like to be able to set the number of columns for the list and have the items on the list split between the columns. 

Bonus: Display context in the “edit list items” view. It would be nice if the first few words of the heading text or content text shown on the List Items view under the general tab.

**Comment by Mass-Care** [comment]
I would also like to see the these items, but most importantly is naming or displaying context in the "edit list items" view. 

Currently I have a list of 30+ legislators and there is no way to differentiate between them in the editing view! Here's a screenshot to be extra clear. We are going to have to abandon this way to listing cosponsors because it's just not useable. 

<img width="1259" alt="Screenshot 2023-01-20 at 12 52 56 PM" src="https://user-images.githubusercontent.com/123206956/213797406-8ee4981d-af7a-4f60-b814-fdfb241f88b6.png">

**Comment by jodzeee** [comment]
Just this week, I was thinking about suggesting something along these lines for other modules as well. Like the Testimonial module (probably others I'm not thinking of at the moment). It is really time consuming to add and edit individual items.

**Comment by jodzeee** [comment]
Revisiting this one. I would love to have a way to bulk add/delete. Maybe like Gravity Forms?

And I agree that not being able to view the list items makes it unusable.

**Comment by codente** [comment]
List item issue is fixed in 2.8

**Comment by jodzeee** [comment]
Good to hear! I was just using PowerPack's and the fact you can copy/paste directly into each list item is an improvement to having to click each one to add the text. Still not quite bulk, but a lot less clicks.

**Comment by codente** [comment]
Part 1 of this is now done and out in 2.10
